######################################################################
# Automatically generated by qmake (2.01a) Thu May 8 16:30:59 2025
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calculator.h
SOURCES += calculator.cpp main.cpp
