# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yolov7_LPR.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 620)
        MainWindow.setWindowTitle("YOLOv7 车牌识别系统")
        MainWindow.setStyleSheet("""
    QMainWindow, QWidget {
        background-color: #1a1a2e;
        color: #e0e0e0;
        font-family: 'Microsoft YaHei', sans-serif;
    }
    QPushButton {
        background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
            stop:0 #0f3460, stop:1 #16213e);
        color: #00d4ff;
        border: 1px solid #00d4ff;
        border-radius: 6px;
        font-size: 14px;
        padding: 6px 12px;
    }
    QPushButton:hover {
        background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
            stop:0 #00d4ff, stop:1 #0f3460);
        color: #1a1a2e;
    }
    QPushButton:pressed {
        background-color: #00a8cc;
    }
    QTextBrowser {
        background-color: #16213e;
        color: #00d4ff;
        border: 1px solid #0f3460;
        border-radius: 4px;
        font-size: 13px;
    }
    QLabel {
        color: #e0e0e0;
    }
    QStatusBar {
        background-color: #0f3460;
        color: #00d4ff;
        font-size: 12px;
    }
""")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 611, 381))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_2.setPalette(palette)
        self.label_2.setStyleSheet("QLabel{\n"
"    \n"
"    border:1px solid #717171;\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(240, 430, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.PB1 = QtWidgets.QPushButton(self.centralwidget)
        self.PB1.setGeometry(QtCore.QRect(60, 480, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(16)
        self.PB1.setFont(font)
        self.PB1.setObjectName("PB1")
        self.PB2 = QtWidgets.QPushButton(self.centralwidget)
        self.PB2.setGeometry(QtCore.QRect(250, 480, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(16)
        self.PB2.setFont(font)
        self.PB2.setObjectName("PB2")
        self.PB3 = QtWidgets.QPushButton(self.centralwidget)
        self.PB3.setGeometry(QtCore.QRect(690, 480, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(16)
        self.PB3.setFont(font)
        self.PB3.setObjectName("PB3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(640, 40, 281, 231))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(710, 290, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 0, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(640, 330, 281, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"    \n"
"    border:1px solid #717171;\n"
"\n"
"}\n"
"")
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(710, 430, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.PB4 = QtWidgets.QPushButton(self.centralwidget)
        self.PB4.setGeometry(QtCore.QRect(440, 480, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(16)
        self.PB4.setFont(font)
        self.PB4.setObjectName("PB4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 942, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        for lbl in [self.label_1, self.label_3, self.label_4, self.label_5]:
            lbl.setStyleSheet("color: #00d4ff; font-weight: bold;")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "视频/图片窗口"))
        self.label_1.setText(_translate("MainWindow", "视频/图片"))
        self.PB1.setText(_translate("MainWindow", "打开文件"))
        self.PB2.setText(_translate("MainWindow", "开始检测"))
        self.PB3.setText(_translate("MainWindow", "退出"))
        self.label_3.setText(_translate("MainWindow", "检测结果"))
        self.label_4.setText(_translate("MainWindow", "YOLOv7车牌识别系统"))
        self.label_5.setText(_translate("MainWindow", "耗时"))
        self.PB4.setText(_translate("MainWindow", "打开/关闭摄像头"))
